#!/bin/bash
# ─── Start Claude Code with Channels Telegram plugin ────────────────────────
# Created by 9 on 2026-04-10 during Path 2 Phase 1 launch.
#
# Usage:
#   bash start-channels.sh
#
# What it does:
#   Launches Claude Code in interactive mode with the Telegram channels plugin
#   enabled. The Telegram MCP server starts polling immediately, so a fresh
#   pairing code can be generated by DMing the bot.
#
# After this launches:
#   1. A new 9 session starts in this terminal
#   2. Jasson DMs @AiNFLGMbot on his iPhone with any message
#   3. The bot replies with a 6-character pairing code
#   4. Jasson tells the new 9 the code
#   5. New 9 runs the pairing step and verifies
#
# Pre-conditions verified before launch:
#   - Plugin installed (checked in /Users/jassonfishback/.claude/plugins/installed_plugins.json)
#   - Token configured (in ~/.claude/channels/telegram/.env)
#   - Policy set to "pairing" mode (in ~/.claude/channels/telegram/access.json)
# ──────────────────────────────────────────────────────────────────────────────

set -e
cd "$(dirname "$0")"

echo "═══════════════════════════════════════════════════════════════"
echo "  9 — Starting Claude Code with Channels Telegram enabled"
echo "═══════════════════════════════════════════════════════════════"

# Sanity checks
if [ ! -f "$HOME/.claude/channels/telegram/.env" ]; then
  echo "ERROR: ~/.claude/channels/telegram/.env missing. Token not configured."
  exit 1
fi
if ! grep -q "TELEGRAM_BOT_TOKEN=" "$HOME/.claude/channels/telegram/.env"; then
  echo "ERROR: TELEGRAM_BOT_TOKEN missing from ~/.claude/channels/telegram/.env"
  exit 1
fi

echo "✓ Plugin token configured"
echo "✓ Starting Claude Code with --channels flag"
echo ""
echo "NEXT STEP once Claude starts: DM @AiNFLGMbot on your iPhone with any message."
echo "The bot will reply with a 6-character pairing code. Tell the new 9 the code."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""

exec claude --channels plugin:telegram@claude-plugins-official
