-- 9 Enterprises Command Hub — Supabase Schema
-- Run this in the Supabase SQL editor to initialize your database.

-- ============================================================
-- COMPANIES
-- The portfolio. Each silo in the org chart gets a row.
-- ============================================================
create table if not exists companies (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text not null unique,         -- url-safe identifier e.g. "ainflgm"
  status      text not null default 'active'
                check (status in ('active', 'paused', 'archived', 'concept')),
  description text,
  revenue     numeric(12,2) default 0,      -- current MRR in USD
  expenses    numeric(12,2) default 0,      -- current monthly burn in USD
  created_at  timestamptz not null default now()
);

-- ============================================================
-- TASKS
-- Every action item, checkbox, priority that 9 or the Owner tracks.
-- ============================================================
create table if not exists tasks (
  id           uuid primary key default gen_random_uuid(),
  title        text not null,
  description  text,
  status       text not null default 'todo'
                 check (status in ('todo', 'in_progress', 'blocked', 'done', 'cancelled')),
  priority     text not null default 'medium'
                 check (priority in ('critical', 'high', 'medium', 'low')),
  company_id   uuid references companies(id) on delete set null,
  due_date     date,
  owner_notes  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Auto-update updated_at on any row change
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger tasks_updated_at
  before update on tasks
  for each row execute function update_updated_at_column();

-- ============================================================
-- DRAFT ROOM
-- Ideas → Greenlit → Owner Review → In Development → Ready to Market
-- ============================================================
create table if not exists draft_room (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,
  pitch            text,                    -- one-liner value prop
  status           text not null default 'idea'
                     check (status in (
                       'idea',
                       'greenlit',
                       'owner_review',
                       'in_development',
                       'ready_to_market',
                       'shipped',
                       'killed'
                     )),
  owner            text,                    -- who owns this card (e.g. "9", "Tee", "Jasson")
  effort           text,                    -- e.g. "3 days", "2 weeks"
  revenue_category text,                    -- e.g. "subscription", "affiliate", "one-time"
  projected_mrr    numeric(10,2),           -- projected monthly recurring revenue
  priority         text not null default 'medium'
                     check (priority in ('critical', 'high', 'medium', 'low')),
  tags             text[],                  -- e.g. '{sports,ai,mobile}'
  ip_notes         text,                    -- intellectual property / competitive moat notes
  go_no_go         text,                    -- criteria for greenlight
  created_at       timestamptz not null default now()
);

-- ============================================================
-- MESSAGES
-- Chat history between Owner and 9. Persists across sessions.
-- ============================================================
create table if not exists messages (
  id         uuid primary key default gen_random_uuid(),
  sender     text not null,                 -- 'owner' | '9' | 'system'
  content    text not null,
  channel    text not null default 'command_hub'
               check (channel in ('command_hub', 'telegram', 'imessage', 'email', 'voice')),
  created_at timestamptz not null default now()
);

-- ============================================================
-- DAILY BRIEFINGS
-- Auto-generated by 9 each morning. Surfaced in Mission Control widget.
-- ============================================================
create table if not exists daily_briefings (
  id                   uuid primary key default gen_random_uuid(),
  wins                 text[],              -- array of win bullets
  blockers             text[],              -- array of blocker bullets
  recommended_actions  text[],              -- 3 recommended actions for Owner
  created_at           timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY (basic setup — tighten before production)
-- ============================================================
alter table companies       enable row level security;
alter table tasks           enable row level security;
alter table draft_room      enable row level security;
alter table messages        enable row level security;
alter table daily_briefings enable row level security;

-- For now: authenticated users can read/write everything.
-- Replace these with specific Owner-only policies before launch.
create policy "authenticated full access — companies"
  on companies for all to authenticated using (true) with check (true);

create policy "authenticated full access — tasks"
  on tasks for all to authenticated using (true) with check (true);

create policy "authenticated full access — draft_room"
  on draft_room for all to authenticated using (true) with check (true);

create policy "authenticated full access — messages"
  on messages for all to authenticated using (true) with check (true);

create policy "authenticated full access — daily_briefings"
  on daily_briefings for all to authenticated using (true) with check (true);

-- ============================================================
-- SEED DATA — starter rows so the app isn't empty on first run
-- ============================================================
insert into companies (name, slug, status, description, revenue, expenses) values
  ('AiNFLGM',    'ainflgm',    'active',  'AI-powered NFL general manager simulation', 0, 0),
  ('FreeAgent9', 'freeagent9', 'active',  'Real estate deals without realtors',         0, 0),
  ('Jules',      'jules',      'concept', 'AI scheduling assistant for Jamie',           0, 0),
  ('Rapid Mortgage', 'rapid',  'active',  'Mortgage origination — Cincinnati market',   0, 0)
on conflict (slug) do nothing;

insert into daily_briefings (wins, blockers, recommended_actions) values (
  array[
    'Command Hub scaffolded and ready for Phase 1 build',
    'Supabase schema live with all five tables'
  ],
  array[
    'No live data yet — real-time APIs pending Phase 2'
  ],
  array[
    'Connect Supabase project and run npm install',
    'Assign Phase 1 task owners in Draft Room',
    'Review branding on Mission Control before sharing'
  ]
);
